<a href="https://colab.research.google.com/github/markbriers/data-science-jupyter/blob/main/week3_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals 2 (Week 3)

My (new) email address: mark.briers@test-and-trace.nhs.uk

## Module: Learning outcomes

* Describe the six stages of a data processing pipeline (using CRISP-DM)

* Demonstrate an understanding of the python programming language through the production of elementary data analysis programme

* Analyse at least three different data sources by applying at least one python data processing library to extract and explore pertinent features

* Be able to design a set of data requirements for a specified business problem

* Describe and apply (using the python programming language) the main approaches to supervised learning for a given classification problem

* Understand the use cases of Big Data technology (in particular Spark)

* Produce a report including appropriate data visualisations covering the analysis of a business problem using a data science based approach

## Week 3: Learning outcome

* At the end of week 3, you will be able to use Python to read data from a file on the internet. You will be able to compute elementary statistics from these data.

***

### Recap: arrays and indexing

In [ ]:
import numpy as np

Indexing a Python array can be performed by specifying up to three values, separated by two colons. The index format is as follows: _inclusive_start:exclusive_end:stride_

In [ ]:
# Build array/vector:
x = np.linspace(1, 10, 10)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
print(x[0])  # first element
print(x[2])  # third element
print(x[-1]) # last element
print(x[-2]) # second to last element
print(x[1:4])     # second to fourth element. Element 5 is not included
print(x[0:-1:2])  # every other element
print(x[:])       # print the whole vector
print(x)          # print the whole vector
print(x[-1:0:-1]) # reverse the vector (but remove the starting element)
print(x[::-1])    # reverse the vector

1.0
3.0
10.0
9.0
[2. 3. 4.]
[1. 3. 5. 7. 9.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


Taken from: https://docs.python.org/release/2.3.5/whatsnew/section-slices.html

## An introduction to Pandas - towards data science!

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language (from https://pandas.pydata.org/). Some of the material in this notebook follows: https://jakevdp.github.io/PythonDataScienceHandbook/index.html

We will start by importing numpy and pandas:

In [ ]:
import pandas as pd

### Pandas Series

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The Series instance above has a set of *values* and an *index*. At this stage, it is conceptually similar to a numpy array. In fact, the values are a numpy array:

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

We can obtain entries from the series in a similar way to a numpy array:

In [ ]:
data[1]

0.5

In [ ]:
print(data[2:])    # print all elements beginning at the third
print("--")
print(data[1:3])   # print the second and third element (not the fourth)
print("--")
print(data[::-1])  # print all elements, in reverse order

2    0.75
3    1.00
dtype: float64
--
1    0.50
2    0.75
dtype: float64
--
3    1.00
2    0.75
1    0.50
0    0.25
dtype: float64


So why do we need this object when we have NumPy arrays? We can use the *index* to define non-integer indexes:

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['Mon', 'Tue', 'Wed', 'Thur'])
data

Mon     0.25
Tue     0.50
Wed     0.75
Thur    1.00
dtype: float64

In [ ]:
data['Thur']

1.0

We can even use non-contiguous indexes (confusingly?):

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [ ]:
data[7]

1.0

Now that we have an index which no longer corresponds to the row number, how do we access the individual rows (e.g. the second row)?

In [ ]:
data.iloc[1]

0.5

We can construct Series objects by creating a python *dictionary* object:

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['New York']

19651127

And we can then slice the series:

In [ ]:
population['Texas':]

Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

We can test to see whether rows exist within the Series:

In [ ]:
'Texas' in population

True

In [ ]:
'New Mexico' in population

False

### Pandas DataFrame

One way to think of a Series is a single colume with row labels. A *DataFrame* extends this concept to a two-dimensional array, that is, a representation of a table (think spreadsheet) where each row *and* column can have a label.

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'New York': 3327999,
                   'Florida': 19552860,
                   'Illinois': 12882135}
area_dict = {'California': 423967,
             'Texas': 695662,
             'New York': 141297,
             'Florida': 170312,
             'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [ ]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [ ]:
type(states.values)

numpy.ndarray

In [ ]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

We can access a specific cell value as follows:

In [ ]:
states.at['Texas','population']

26448193

We can acquire a single row using the *loc* function:

In [ ]:
states.loc['California']

population    38332521
area            423967
Name: California, dtype: int64

And we can acquire a single row using an integer index using the iloc function:

In [ ]:
states.iloc[1]

population    26448193
area            695662
Name: Texas, dtype: int64

In [ ]:
states.iloc[1].population

26448193

The previous line of code extracts the second line of data and the column titled 'population'.

We can construct new columns from existing columns:

In [ ]:
states['density'] = states['population'] / states['area']
states

population    area  population density     density
California    38332521  423967           90.413926   90.413926
Texas         26448193  695662           38.018740   38.018740
New York      19651127  141297          139.076746  139.076746
Florida       19552860  170312          114.806121  114.806121
Illinois      12882135  149995           85.883763   85.883763

We can switch the order of the rows and columns (transpose the DataFrame):

In [ ]:
print(states.T)
print(states.T.iloc[1])

                      California         Texas  ...       Florida      Illinois
population          3.833252e+07  2.644819e+07  ...  1.955286e+07  1.288214e+07
area                4.239670e+05  6.956620e+05  ...  1.703120e+05  1.499950e+05
population density  9.041393e+01  3.801874e+01  ...  1.148061e+02  8.588376e+01

[3 rows x 5 columns]
California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois      149995.0
Name: area, dtype: float64


We can slice the DataFrame by integer location:

In [ ]:
states.iloc[:3, :2]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [ ]:
states.T.iloc[:3,:2]

California         Texas
population          3.833252e+07  2.644819e+07
area                4.239670e+05  6.956620e+05
population density  9.041393e+01  3.801874e+01

We can also extract specific columns based on computed logic (using the index names) and *loc* function:

In [ ]:
states.loc[states.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

We can use numpy functions to perform operations on DataFrames, which preserves the indexes:

In [ ]:
logStates = np.log(states)

In [ ]:
logStates

population       area  population density   density
California   17.461809  12.957411            4.504398  4.504398
Texas        17.090698  13.452619            3.638079  3.638079
New York     16.793645  11.858619            4.935026  4.935026
Florida      16.788632  12.045387            4.743245  4.743245
Illinois     16.371352  11.918357            4.452995  4.452995

We can compute basic summary statistics for each of the columns listed above:

In [ ]:
states.describe()

population           area  population density     density
count  5.000000e+00       5.000000            5.000000    5.000000
mean   2.337337e+07  316246.600000           93.639859   93.639859
std    9.640386e+06  242437.411951           37.672251   37.672251
min    1.288214e+07  141297.000000           38.018740   38.018740
25%    1.955286e+07  149995.000000           85.883763   85.883763
50%    1.965113e+07  170312.000000           90.413926   90.413926
75%    2.644819e+07  423967.000000          114.806121  114.806121
max    3.833252e+07  695662.000000          139.076746  139.076746

## Loading data into a DataFrame

We can load data from a CSV file into a DataFrame as follows:

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv')

In [ ]:
df.shape

(194, 2)

In [ ]:
df

Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv', index_col=0)

In [ ]:
df

Region
Country                 
Algeria           AFRICA
Angola            AFRICA
Benin             AFRICA
Botswana          AFRICA
Burkina           AFRICA
...                  ...
Paraguay   SOUTH AMERICA
Peru       SOUTH AMERICA
Suriname   SOUTH AMERICA
Uruguay    SOUTH AMERICA
Venezuela  SOUTH AMERICA

[194 rows x 1 columns]

In [ ]:
df.loc['United Kingdom']

Region    EUROPE
Name: United Kingdom, dtype: object

## Case study: COVID-19 data from John Hopkins University

Let's install the Python package _wget_ into colab:

In [ ]:
!pip install wget

  Created wheel for wget: filename=wget-3.2-cp36-none-any.whl size=9682 sha256=dc95d71d6d3be477510d87d56645a37251ac1c136a538e9f1f86948dd476a587
  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [ ]:
import wget

We will grab two files from the internet, one for COVID-19 cases and one for deaths.

In [ ]:
# url of the raw csv dataset
urls = [
    'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',
    'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv',
]
[wget.download(url) for url in urls]

['time_series_covid19_confirmed_global.csv',
 'time_series_covid19_deaths_global.csv']

Let's read these into a dataframe:

In [ ]:
confirmed_df = pd.read_csv('time_series_covid19_confirmed_global.csv')
deaths_df = pd.read_csv('time_series_covid19_deaths_global.csv')

In [ ]:
confirmed_df.head()

Province/State Country/Region       Lat  ...  1/25/21  1/26/21  1/27/21
0            NaN    Afghanistan  33.93911  ...    54672    54750    54854
1            NaN        Albania  41.15330  ...    72812    73691    74567
2            NaN        Algeria  28.03390  ...   105854   106097   106359
3            NaN        Andorra  42.50630  ...     9596     9638     9716
4            NaN         Angola -11.20270  ...    19476    19553    19580

[5 rows x 376 columns]

Let's take a quick look at the column headings:

In [ ]:
print(confirmed_df.columns)
print(deaths_df.columns)

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '1/18/21', '1/19/21', '1/20/21', '1/21/21', '1/22/21', '1/23/21',
       '1/24/21', '1/25/21', '1/26/21', '1/27/21'],
      dtype='object', length=376)
Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '1/18/21', '1/19/21', '1/20/21', '1/21/21', '1/22/21', '1/23/21',
       '1/24/21', '1/25/21', '1/26/21', '1/27/21'],
      dtype='object', length=376)


Let's have a quick look at a summary of the columns:

In [ ]:
confirmed_df.describe()

Lat        Long  ...       1/26/21       1/27/21
count  272.000000  272.000000  ...  2.730000e+02  2.730000e+02
mean    20.639516   23.165585  ...  3.673134e+05  3.694726e+05
std     25.181450   73.696719  ...  1.813808e+06  1.823894e+06
min    -51.796300 -178.116500  ...  0.000000e+00  0.000000e+00
25%      6.105887  -20.026050  ...  8.900000e+02  8.930000e+02
50%     21.805100   20.972650  ...  1.128600e+04  1.128600e+04
75%     41.123000   84.497525  ...  1.532260e+05  1.540830e+05
max     71.706900  178.065000  ...  2.544558e+07  2.559806e+07

[8 rows x 374 columns]

In [ ]:
deaths_df.describe()

Lat        Long  ...        1/26/21        1/27/21
count  272.000000  272.000000  ...     273.000000     273.000000
mean    20.639516   23.165585  ...    7902.864469    7963.842491
std     25.181450   73.696719  ...   33808.458180   34087.686744
min    -51.796300 -178.116500  ...       0.000000       0.000000
25%      6.105887  -20.026050  ...       6.000000       6.000000
50%     21.805100   20.972650  ...     147.000000     151.000000
75%     41.123000   84.497525  ...    2477.000000    2553.000000
max     71.706900  178.065000  ...  425252.000000  429195.000000

[8 rows x 374 columns]

***

## Week 3: Learning outcome

* At the end of week 3, you will be able to use Python to read data from a file on the internet. You will be able to compute elementary statistics from these data.

## Exercises

Mandatory exercises:

- [ ] Replicate all of the code in this notebook.
- [ ] Introduce COVID-19 recoveries into the analysis above. 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'. What do you notice about the mean number of recoveries as a function of time?