<a href="https://colab.research.google.com/github/markbriers/data-science-jupyter/blob/main/week3_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals 2 (Week 3)

My email address: mbriers@turing.ac.uk

## Module: Learning outcomes

* Describe the six stages of a data processing pipeline (using CRISP-DM)

* Demonstrate an understanding of the python programming language through the production of elementary data analysis programme

* Analyse at least three different data sources by applying at least one python data processing library to extract and explore pertinent features

* Be able to design a set of data requirements for a specified business problem

* Describe and apply (using the python programming language) the main approaches to supervised learning for a given classification problem

* Understand the use cases of Big Data technology (in particular Spark)

* Produce a report including appropriate data visualisations covering the analysis of a business problem using a data science based approach

## Week 3: Learning outcome

* At the end of week 3, you will be able to use Python to read data from a file on the internet. You will be able to compute elementary statistics from these data.

***

### Recap: arrays and indexing

In [ ]:
import numpy as np
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

Indexing a Python array can be performed by specifying up to three values, separated by two colons. The index format is as follows: _inclusive_start:exclusive_end:stride_

In [ ]:
# Build array/vector:
x = np.linspace(1, 10, 10)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
print(x[0])  # first element
print(x[2])  # third element
print(x[-1]) # last element
print(x[-2]) # second to last element
print(x[1:4])     # second to fourth element. Element 5 is not included
print(x[0:-1:2])  # every other element
print(x[:])       # print the whole vector
print(x)          # print the whole vector
print(x[-1:0:-1]) # reverse the vector (but remove the starting element)
print(x[::-1])    # reverse the vector

1.0
3.0
10.0
9.0
[2. 3. 4.]
[1. 3. 5. 7. 9.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


Taken from: https://docs.python.org/release/2.3.5/whatsnew/section-slices.html

## An introduction to Pandas - towards data science!

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language (from https://pandas.pydata.org/). Some of the material in this notebook follows: https://jakevdp.github.io/PythonDataScienceHandbook/index.html

We will start by importing numpy and pandas:

In [ ]:
import pandas as pd

### Pandas Series

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The Series instance above has a set of *values* and an *index*. At this stage, it is conceptually similar to a numpy array. In fact, the values are a numpy array:

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

We can obtain entries from the series in a similar way to a numpy array:

In [ ]:
data[1]

0.5

In [ ]:
print(data[2:])    # print all elements beginning at the third
print("--")
print(data[1:3])   # print the second and third element (not the fourth)
print("--")
print(data[::-1])  # print all elements, in reverse order

2    0.75
3    1.00
dtype: float64
--
1    0.50
2    0.75
dtype: float64
--
3    1.00
2    0.75
1    0.50
0    0.25
dtype: float64


So why do we need this object when we have NumPy arrays? We can use the *index* to define non-integer indexes:

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['Mon', 'Tue', 'Wed', 'Thur'])
data

Mon     0.25
Tue     0.50
Wed     0.75
Thur    1.00
dtype: float64

In [ ]:
data['Thur']

1.0

We can even use non-contiguous indexes (confusingly?):

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [ ]:
data[7]

1.0

Now that we have an index which no longer corresponds to the row number, how do we access the individual rows (e.g. the second row)?

In [ ]:
data.iloc[1]

0.5

We can construct Series objects by creating a python *dictionary* object:

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['New York']

19651127

And we can then slice the series:

In [ ]:
population['Texas':]

Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

We can test to see whether rows exist within the Series:

In [ ]:
'Texas' in population

True

In [ ]:
'New Mexico' in population

False

### Pandas DataFrame

One way to think of a Series is a single colume with row labels. A *DataFrame* extends this concept to a two-dimensional array, that is, a representation of a table (think spreadsheet) where each row *and* column can have a label.

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'New York': 3327999,
                   'Florida': 19552860,
                   'Illinois': 12882135}
area_dict = {'California': 423967,
             'Texas': 695662,
             'New York': 141297,
             'Florida': 170312,
             'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [ ]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [ ]:
type(states.values)

numpy.ndarray

In [ ]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

We can access a specific cell value as follows:

In [ ]:
states.at['Texas','population']

26448193

We can acquire a single row using the *loc* function:

In [ ]:
states.loc['California']

population    38332521
area            423967
Name: California, dtype: int64

And we can acquire a single row using an integer index using the iloc function:

In [ ]:
states.iloc[1]

population    26448193
area            695662
Name: Texas, dtype: int64

In [ ]:
states.iloc[1].population

26448193

The previous line of code extracts the second line of data and the column titled 'population'.

We can construct new columns from existing columns:

In [ ]:
states['density'] = states['population'] / states['area']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

We can switch the order of the rows and columns (transpose the DataFrame):

In [ ]:
print(states.T)
print(states.T.iloc[1])

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01  
California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois      149995.0
Name: area, dtype: float64


We can slice the DataFrame by integer location:

In [ ]:
states.iloc[:3, :2]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [ ]:
states.T.iloc[:3,:2]

California         Texas
population  3.833252e+07  2.644819e+07
area        4.239670e+05  6.956620e+05
density     9.041393e+01  3.801874e+01

We can also extract specific columns based on computed logic (using the index names) and *loc* function:

In [ ]:
states.loc[states.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

We can use numpy functions to perform operations on DataFrames, which preserves the indexes:

In [ ]:
logStates = np.log(states)

In [ ]:
logStates

population       area   density
California   17.461809  12.957411  4.504398
Texas        17.090698  13.452619  3.638079
New York     16.793645  11.858619  4.935026
Florida      16.788632  12.045387  4.743245
Illinois     16.371352  11.918357  4.452995

We can compute basic summary statistics for each of the columns listed above:

In [ ]:
states.describe()

population           area     density
count  5.000000e+00       5.000000    5.000000
mean   2.337337e+07  316246.600000   93.639859
std    9.640386e+06  242437.411951   37.672251
min    1.288214e+07  141297.000000   38.018740
25%    1.955286e+07  149995.000000   85.883763
50%    1.965113e+07  170312.000000   90.413926
75%    2.644819e+07  423967.000000  114.806121
max    3.833252e+07  695662.000000  139.076746

## Loading data into a DataFrame

We can load data from a CSV file into a DataFrame as follows:

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv')

In [ ]:
df.shape

(194, 2)

In [ ]:
df

Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv', index_col=0)

In [ ]:
df

Region
Country                 
Algeria           AFRICA
Angola            AFRICA
Benin             AFRICA
Botswana          AFRICA
Burkina           AFRICA
...                  ...
Paraguay   SOUTH AMERICA
Peru       SOUTH AMERICA
Suriname   SOUTH AMERICA
Uruguay    SOUTH AMERICA
Venezuela  SOUTH AMERICA

[194 rows x 1 columns]

In [ ]:
df.loc['United Kingdom']

Region    EUROPE
Name: United Kingdom, dtype: object

## Case study: COVID-19 data from John Hopkins University

We will grab two files from the internet, one for COVID-19 cases and one for deaths. Let's read these into a dataframe:

In [ ]:
confirmed_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
deaths_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')

In [ ]:
confirmed_df.head()

Province/State Country/Region       Lat       Long  1/22/20  1/23/20  \
0            NaN    Afghanistan  33.93911  67.709953        0        0   
1            NaN        Albania  41.15330  20.168300        0        0   
2            NaN        Algeria  28.03390   1.659600        0        0   
3            NaN        Andorra  42.50630   1.521800        0        0   
4            NaN         Angola -11.20270  17.873900        0        0   

   1/24/20  1/25/20  1/26/20  1/27/20  ...  2/28/23  3/1/23  3/2/23  3/3/23  \
0        0        0        0        0  ...   209322  209340  209358  209362   
1        0        0        0        0  ...   334391  334408  334408  334427   
2        0        0        0        0  ...   271441  271448  271463  271469   
3        0        0        0        0  ...    47866   47875   47875   47875   
4        0        0        0        0  ...   105255  105277  105277  105277   

   3/4/23  3/5/23  3/6/23  3/7/23  3/8/23  3/9/23  
0  209369  209390  209406  209436  209451  209451  
1  334427  334427  334427  334427  334443  334457  
2  271469  271477  271477  271490  271494  271496  
3   47875   47875   47875   47875   47890   47890  
4  105277  105277  105277  105277  105288  105288  

[5 rows x 1147 columns]

Let's take a quick look at the column headings:

In [ ]:
print(confirmed_df.columns)
print(deaths_df.columns)

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '2/28/23', '3/1/23', '3/2/23', '3/3/23', '3/4/23', '3/5/23', '3/6/23',
       '3/7/23', '3/8/23', '3/9/23'],
      dtype='object', length=1147)
Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '2/28/23', '3/1/23', '3/2/23', '3/3/23', '3/4/23', '3/5/23', '3/6/23',
       '3/7/23', '3/8/23', '3/9/23'],
      dtype='object', length=1147)


Let's have a quick look at a summary of the columns:

In [ ]:
confirmed_df.describe()

Lat        Long     1/22/20     1/23/20     1/24/20     1/25/20  \
count  287.000000  287.000000  289.000000  289.000000  289.000000  289.000000   
mean    19.718719   22.182084    1.927336    2.273356    3.266436    4.972318   
std     25.956609   77.870931   26.173664   26.270191   32.707271   45.523871   
min    -71.949900 -178.116500    0.000000    0.000000    0.000000    0.000000   
25%      4.072192  -32.823050    0.000000    0.000000    0.000000    0.000000   
50%     21.512583   20.939400    0.000000    0.000000    0.000000    0.000000   
75%     40.401784   89.224350    0.000000    0.000000    0.000000    0.000000   
max     71.706900  178.065000  444.000000  444.000000  549.000000  761.000000   

           1/26/20      1/27/20      1/28/20      1/29/20  ...       2/28/23  \
count   289.000000   289.000000   289.000000   289.000000  ...  2.890000e+02   
mean      7.335640    10.134948    19.307958    21.346021  ...  2.336755e+06   
std      63.623197    85.724481   210.329649   211.628535  ...  8.506608e+06   
min       0.000000     0.000000     0.000000     0.000000  ...  0.000000e+00   
25%       0.000000     0.000000     0.000000     0.000000  ...  1.456700e+04   
50%       0.000000     0.000000     0.000000     0.000000  ...  1.032480e+05   
75%       0.000000     0.000000     0.000000     0.000000  ...  1.051998e+06   
max    1058.000000  1423.000000  3554.000000  3554.000000  ...  1.034435e+08   

             3/1/23        3/2/23        3/3/23        3/4/23        3/5/23  \
count  2.890000e+02  2.890000e+02  2.890000e+02  2.890000e+02  2.890000e+02   
mean   2.337519e+06  2.338173e+06  2.338805e+06  2.338992e+06  2.339187e+06   
std    8.511285e+06  8.514488e+06  8.518031e+06  8.518408e+06  8.518645e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    1.456700e+04  1.456700e+04  1.456700e+04  1.456700e+04  1.456700e+04   
50%    1.032480e+05  1.032480e+05  1.032480e+05  1.032480e+05  1.032480e+05   
75%    1.052122e+06  1.052247e+06  1.052382e+06  1.052519e+06  1.052664e+06   
max    1.035339e+08  1.035898e+08  1.036487e+08  1.036508e+08  1.036470e+08   

             3/6/23        3/7/23        3/8/23        3/9/23  
count  2.890000e+02  2.890000e+02  2.890000e+02  2.890000e+02  
mean   2.339387e+06  2.339839e+06  2.340460e+06  2.341073e+06  
std    8.519346e+06  8.521641e+06  8.524968e+06  8.527765e+06  
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%    1.456700e+04  1.456700e+04  1.456700e+04  1.456700e+04  
50%    1.032480e+05  1.032480e+05  1.032480e+05  1.032480e+05  
75%    1.052664e+06  1.052926e+06  1.053068e+06  1.053213e+06  
max    1.036555e+08  1.036909e+08  1.037558e+08  1.038027e+08  

[8 rows x 1145 columns]

In [ ]:
deaths_df.describe()

Lat        Long     1/22/20     1/23/20     1/24/20     1/25/20  \
count  287.000000  287.000000  289.000000  289.000000  289.000000  289.000000   
mean    19.718719   22.182084    0.058824    0.062284    0.089965    0.145329   
std     25.956609   77.870931    1.000000    1.001525    1.413797    2.353998   
min    -71.949900 -178.116500    0.000000    0.000000    0.000000    0.000000   
25%      4.072192  -32.823050    0.000000    0.000000    0.000000    0.000000   
50%     21.512583   20.939400    0.000000    0.000000    0.000000    0.000000   
75%     40.401784   89.224350    0.000000    0.000000    0.000000    0.000000   
max     71.706900  178.065000   17.000000   17.000000   24.000000   40.000000   

          1/26/20     1/27/20     1/28/20     1/29/20  ...       2/28/23  \
count  289.000000  289.000000  289.000000  289.000000  ...  2.890000e+02   
mean     0.193772    0.283737    0.453287    0.460208  ...  2.378091e+04   
std      3.060245    4.471644    7.353103    7.353616  ...  9.337339e+04   
min      0.000000    0.000000    0.000000    0.000000  ...  0.000000e+00   
25%      0.000000    0.000000    0.000000    0.000000  ...  6.600000e+01   
50%      0.000000    0.000000    0.000000    0.000000  ...  9.440000e+02   
75%      0.000000    0.000000    0.000000    0.000000  ...  8.721000e+03   
max     52.000000   76.000000  125.000000  125.000000  ...  1.119917e+06   

             3/1/23        3/2/23        3/3/23        3/4/23        3/5/23  \
count  2.890000e+02  2.890000e+02  2.890000e+02  2.890000e+02  2.890000e+02   
mean   2.378707e+04  2.379249e+04  2.379697e+04  2.379793e+04  2.379844e+04   
std    9.341836e+04  9.345110e+04  9.347703e+04  9.347884e+04  9.347810e+04   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    6.600000e+01  6.600000e+01  6.600000e+01  6.600000e+01  6.600000e+01   
50%    9.440000e+02  9.520000e+02  9.520000e+02  9.520000e+02  9.520000e+02   
75%    8.721000e+03  8.721000e+03  8.721000e+03  8.721000e+03  8.721000e+03   
max    1.120897e+06  1.121658e+06  1.122165e+06  1.122172e+06  1.122134e+06   

             3/6/23        3/7/23        3/8/23        3/9/23  
count  2.890000e+02  2.890000e+02  2.890000e+02  2.890000e+02  
mean   2.379971e+04  2.380290e+04  2.380790e+04  2.381246e+04  
std    9.348106e+04  9.349767e+04  9.352985e+04  9.355567e+04  
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%    6.600000e+01  6.600000e+01  6.600000e+01  6.600000e+01  
50%    9.520000e+02  9.520000e+02  9.520000e+02  9.520000e+02  
75%    8.721000e+03  8.721000e+03  8.727000e+03  8.727000e+03  
max    1.122181e+06  1.122516e+06  1.123246e+06  1.123836e+06  

[8 rows x 1145 columns]

***

## Week 3: Learning outcome

* At the end of week 3, you will be able to use Python to read data from a file on the internet. You will be able to compute elementary statistics from these data.

## Exercises

Mandatory exercises:

- [ ] Replicate all of the code in this notebook.
- [ ] Introduce COVID-19 recoveries into the analysis above. 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'. What do you notice about the mean number of recoveries as a function of time?